### ISSUE TITLE
No (built-in) way to resume the frame buffer

### ISSUE THREAD

**Issue by Andon-A** [adafruit/Adafruit_CircuitPython_VC0706#16]
Picked up one of these wonderful little cameras, loaded up the example. Easy to modify to save directly to the M4's built-in memory. And hey, it works!

Except. You get precisely one image. The program sends the commands to stop the frame buffer, and then take the picture, but there's no command to tell it to resume the frame buffer. Similarly, there's no command to manually do so either.

I poked at the file and while there's a definition for _RESUMEFRAME, it's not used anywhere. I've tried sending it manually via _send_command but have had no luck so far. I'm going to take a look at the Arduino library and see if I can glean things from that.

**Comment by ladyada** [comment]
good luck!

**Comment by Andon-A** [comment]
That was... a lot easier than I expected, honestly. Took a look at the Arduino library, poked a few times at things in CP, and had it working. Pull request should be incoming.... provided I've done GitHub stuff correctly.

**Comment by Andon-A** [comment]
Resolved with PR #17
